[book]
authors = ["Alex P."]
language = "en"
multilingual = false
src = "docs"
title = "Cell Manual"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
curly-quotes = true
git-repository-url = "https://github.com/open-slicer/cell"